input_folder: input/paper
output_folder: output/paper
csv_delimiter: ";"
input_encoding: "utf-8"
valid_persons:
  - a
  - b
  - m
generate_text_report: true
generate_csv_report: true
archive_old_files: true
